#lang pollen

definite?, countable?, singular?

◊q[ooo]{the. the graphs is presented with this text.} provided line graph describes what happens when we consume ◊q[xox]{zero. Thought that food is general so it should be uncountable, but the text use plural. Is this a signal that this "food" is more specifc that enables it to be countable?} sweet foods in the form of ◊q[xx]{zero. general concept} fruit sugar, ◊q[xx]{zero. general concept} honey, and ◊q[xx]{zero. general concept} cane sugar, and how ◊q[xox]{zero. verb is "create". The "acid levels" is not specifc.} resulting increased acid levels create ◊q[xx]{zero. "tooth decay" narrows the scope of "potential", but it's not complete.} potential for ◊q[xx]{zero. general concept} tooth decay.

As is presented in ◊q[ooo]{the. stated in the first paragraph.} graph, ◊q[ox]{the. In the first paragraph, the author says about it: "consume sweet foods in the form of fruit sugar, ..."} sugar consumption in ◊q[oox]{the. Same as right before: "form of ..."} various forms leads to ◊q[ox]{the. "resulting increased acid levels" in the first paragraph. General concept->uncountable.} higher acidity, represented by ◊q[xox]{zero. There's no description of "PH levels."} lower PH levels. ◊q[oox]{the, but zero from the use of "these." Definitive judging from the "PH levels" right before.} These PH levels are at their lowest at ◊q[oox]{zero. exception?} 5 minutes after eating ◊q[xx]{zero. Although there's texts of "sugar", since they're generic, we cannot be sure about its speicificity.} sugar, and they gradually increase until they reach 5.5, at which point ◊q[xx]{zero. Same as the explanation of ◊q right before.} tooth decay is no longer likely.

◊q[xx]{zero. Same as the explanation of ◊q right before} Cane sugar is clearly ◊q[ooo]{the. seems it should be "the", but is this specific?} most dangerous type of ◊q[xx]{zero. As before, generic.} sugar, among those represented in ◊q[ooo]{the. we're saying about the graph this text gives us} graph.
